[project]
name = "circle-transaction-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "circle-developer-controlled-wallets>=6.3.0",
    "fastapi[standard]>=0.116.1",
]
